### ISSUE TITLE
any plan to develop a python wrapper?

### ISSUE THREAD

**Issue by jpdeleon** [EnricoCorsaro/DIAMONDS#2]
I saw from your paper that you compared DIAMONDS to Multinest. I believe multinest became more popular to astronomy community recently due to availability of its python wrapper, pymultinest. I wonder if you plan to develop pyDiamonds also for a wider audience reach.

Anyway, thanks for the great software and paper!

**Comment by EnricoCorsaro** [comment]
Hi Jerome, thanks for commenting here!
Sorry I was a bit late to answer. So I definitely agree with you and there exists already a Python wrapper for DIAMONDS, which is available here
https://github.com/MarcoMuellner/PyDIAMONDS

Just consider this is still work in progress and that some of the functionalities of DIAMONDS may not work, or not work correctly. We would also appreciate any feedback from your side in using that tool. Thanks a lot for your interest in this project!
Feel free to ask questions any time.

Enrico

**Comment by jpdeleon** [comment]
Great! Thanks for developing PyDiamonds. I will definitely check it once stable releases become available.
